### ISSUE TITLE
Panic on an any example

### ISSUE THREAD

**Issue by legendiguess** [dhardy/kas#31]
![image](https://user-images.githubusercontent.com/40376451/71147669-45f81800-224b-11ea-89d1-af94a8ff69d9.png)

Maybe i should install something additional?
Steps that i do:
1) clone repository
2) cd kas-wgpu
3) cargo run --exmaple *example name*

Also when i compiled it, some crate require to install cmake, so, i think, you should mention it in some installation guide.

All it was on a linux peppermint 10. Also using last nightly linux gnu toolchain.

**Comment by dhardy** [comment]
Thanks for testing. The steps sound about right, unfortunately I can't tell what's wrong from that error message.

Can you try enabling the backtrace as mentioned (`export RUST_BACKTRACE=1`), and then copying the error into a [gist](https://gist.github.com) please?

Aha, probably CMake is required for the GLSL compiler. Okay, I'll add a note :+1:

**Comment by legendiguess** [comment]
https://gist.github.com/legendiguess/82f4fefce2ecd51df8159454013e8652

**Comment by dhardy** [comment]
Looks like it is [`wgpu::Adapter::request`](https://docs.rs/wgpu/0.4.0/wgpu/struct.Adapter.html#method.request) which fails. What GPU / integrated graphics do you have?

The disadvantage of using a [modern graphics API](https://github.com/gfx-rs/gfx) as the first and only draw backend is that we don't have any other options (yet). Can you try running the [GFX examples](https://github.com/gfx-rs/gfx/tree/master/examples) and see whether any backends are functional (e.g. `gl`)?

I will improve the error message here, but don't expect to have a CPU-based renderer soon.

**Comment by legendiguess** [comment]
I have Intel HD Graphics 500. Just checked gfx example with different backend - only `gl` works.

**Comment by dhardy** [comment]
Sounds like this issue: https://github.com/gfx-rs/wgpu/issues/115.

**Comment by dhardy** [comment]
I improved error handling within `kas_wgpu`: https://github.com/dhardy/kas/commit/e13f1d6b1599c0e7c7fdec07427958a8492c7876

In combination with https://github.com/gfx-rs/wgpu/pull/408 this should improve error messages.

Actually getting things working is rather more work...

**Comment by dhardy** [comment]
I opened #33 to track support for additional targets.

The error message is improved, so I believe this can be closed.
